const countryOptions = [
    { key: 'Canada', text: 'Canada', value: 'CA' },
    { key: 'US', text: 'United States', value: 'US' },
];
const countryOptionsFrench = [
    { key: 'Canada', text: 'Canada', value: 'CA' },
    { key: 'US', text: 'États-Unis', value: 'US' },
];
const canadaProvinceOptions = [
    { key: 'Alberta', text: 'Alberta', value: 'AB' },
    { key: 'BC', text: 'British Columbia', value: 'BC' },
    { key: 'Manitoba', text: 'Manitoba', value: 'MB' },
    { key: 'NB', text: 'New Brunswick', value: 'NB' },
    { key: 'NL', text: 'Newfoundland and Labrador', value: 'NL' },
    { key: 'NS', text: 'Nova Scotia', value: 'NS' },
    { key: 'NT', text: 'Northwest Territories', value: 'NT' },
    { key: 'Nunavut', text: 'Nunavut', value: 'NU' },
    { key: 'Ontario', text: 'Ontario', value: 'ON' },
    { key: 'PEI', text: 'Prince Edward Island', value: 'PE' },
    { key: 'Quebec', text: 'Quebec', value: 'QC' },
    { key: 'Saskatchewan', text: 'Saskatchewan', value: 'SK' },
    { key: 'Yukon', text: 'Yukon', value: 'YT' },
];
const canadaProvinceOptionsFrench = [
    { key: 'Alberta', text: 'Alberta', value: 'AB' },
    { key: 'BC', text: 'Colombie Britannique', value: 'BC' },
    { key: 'Manitoba', text: 'Manitoba', value: 'MB' },
    { key: 'NB', text: 'Nouveau Brunswick', value: 'NB' },
    { key: 'NL', text: 'Terre-Neuve-et-Labrador', value: 'NL' },
    { key: 'NS', text: 'Nouvelle Écosse', value: 'NS' },
    { key: 'NT', text: 'Territoires du Nord-Ouest', value: 'NT' },
    { key: 'Nunavut', text: 'Nunavut', value: 'NU' },
    { key: 'Ontario', text: 'Ontario', value: 'ON' },
    { key: 'PEI', text: 'Île-du-Prince-Édouard', value: 'PE' },
    { key: 'Quebec', text: 'Québec', value: 'QC' },
    { key: 'Saskatchewan', text: 'Saskatchewan', value: 'SK' },
    { key: 'Yukon', text: 'Yukon', value: 'YT' },
];
const usStateOptions = [
    { key: 'Alabama', text: 'Alabama', value: 'AL' },
    { key: 'Alaska', text: 'Alaska', value: 'AK' },
    { key: 'Arizona', text: 'Arizona', value: 'AZ' },
    { key: 'Arkansas', text: 'Arkansas', value: 'AR' },
    { key: 'California', text: 'California', value: 'CA' },
    { key: 'Colorado', text: 'Colorado', value: 'CO' },
    { key: 'Connecticut', text: 'Connecticut', value: 'CT' },
    { key: 'DC', text: 'District of Columbia', value: 'DC' },
    { key: 'Delaware', text: 'Delaware', value: 'DE' },
    { key: 'Florida', text: 'Florida', value: 'FL' },
    { key: 'Georgia', text: 'Georgia', value: 'GA' },
    { key: 'Hawaii', text: 'Hawaii', value: 'HI' },
    { key: 'Idaho', text: 'Idaho', value: 'ID' },
    { key: 'Illinois', text: 'Illinois', value: 'IL' },
    { key: 'Indiana', text: 'Indiana', value: 'IN' },
    { key: 'Iowa', text: 'Iowa', value: 'IA' },
    { key: 'Kansas', text: 'Kansas', value: 'KS' },
    { key: 'Kentucky', text: 'Kentucky', value: 'KY' },
    { key: 'Louisiana', text: 'Louisiana', value: 'LA' },
    { key: 'Maine', text: 'Maine', value: 'ME' },
    { key: 'Maryland', text: 'Maryland', value: 'MD' },
    { key: 'Massachusetts', text: 'Massachusetts', value: 'MA' },
    { key: 'Michigan', text: 'Michigan', value: 'MI' },
    { key: 'Minnesota', text: 'Minnesota', value: 'MN' },
    { key: 'Mississippi', text: 'Mississippi', value: 'MS' },
    { key: 'Missouri', text: 'Missouri', value: 'MO' },
    { key: 'Montana', text: 'Montana', value: 'MT' },
    { key: 'Nebraska', text: 'Nebraska', value: 'NE' },
    { key: 'Nevada', text: 'Nevada', value: 'NV' },
    { key: 'NH', text: 'New Hampshire', value: 'NH' },
    { key: 'NJ', text: 'New Jersey', value: 'NJ' },
    { key: 'NM', text: 'New Mexico', value: 'NM' },
    { key: 'NY', text: 'New York', value: 'NY' },
    { key: 'NC', text: 'North Carolina', value: 'NC' },
    { key: 'ND', text: 'North Dakota', value: 'ND' },
    { key: 'Ohio', text: 'Ohio', value: 'OH' },
    { key: 'Oklahoma', text: 'Oklahoma', value: 'OK' },
    { key: 'Oregon', text: 'Oregon', value: 'OR' },
    { key: 'Pennsylvania', text: 'Pennsylvania', value: 'PA' },
    { key: 'RI', text: 'Rhode Island', value: 'RI' },
    { key: 'SC', text: 'South Carolina', value: 'SC' },
    { key: 'SD', text: 'South Dakota', value: 'SD' },
    { key: 'Tennessee', text: 'Tennessee', value: 'TN' },
    { key: 'Texas', text: 'Texas', value: 'TX' },
    { key: 'Utah', text: 'Utah', value: 'UT' },
    { key: 'Vermont', text: 'Vermont', value: 'VT' },
    { key: 'Virginia', text: 'Virginia', value: 'VA' },
    { key: 'Washington', text: 'Washington', value: 'WA' },
    { key: 'WV', text: 'West Virginia', value: 'WV' },
    { key: 'Wisconsin', text: 'Wisconsin', value: 'WI' },
    { key: 'Wyoming', text: 'Wyoming', value: 'WY' },
];
const usStateOptionsFrench = [
    { key: 'Alabama', text: 'Alabama', value: 'AL' },
    { key: 'Alaska', text: 'Alaska', value: 'AK' },
    { key: 'Arizona', text: 'Arizona', value: 'AZ' },
    { key: 'Arkansas', text: 'Arkansas', value: 'AR' },
    { key: 'California', text: 'Californie', value: 'CA' },
    { key: 'Colorado', text: 'Colorado', value: 'CO' },
    { key: 'Connecticut', text: 'Connecticut', value: 'CT' },
    { key: 'DC', text: 'District de Columbia', value: 'DC' },
    { key: 'Delaware', text: 'Delaware', value: 'DE' },
    { key: 'Florida', text: 'Floride', value: 'FL' },
    { key: 'Georgia', text: 'Géorgie', value: 'GA' },
    { key: 'Hawaii', text: 'Hawaï', value: 'HI' },
    { key: 'Idaho', text: 'Idaho', value: 'ID' },
    { key: 'Illinois', text: 'Illinois', value: 'IL' },
    { key: 'Indiana', text: 'Indiana', value: 'IN' },
    { key: 'Iowa', text: 'Iowa', value: 'IA' },
    { key: 'Kansas', text: 'Kansas', value: 'KS' },
    { key: 'Kentucky', text: 'Kentucky', value: 'KY' },
    { key: 'Louisiana', text: 'Louisiane', value: 'LA' },
    { key: 'Maine', text: 'Maine', value: 'ME' },
    { key: 'Maryland', text: 'Maryland', value: 'MD' },
    { key: 'Massachusetts', text: 'Massachusetts', value: 'MA' },
    { key: 'Michigan', text: 'Michigan', value: 'MI' },
    { key: 'Minnesota', text: 'Minnesota', value: 'MN' },
    { key: 'Mississippi', text: 'Mississippi', value: 'MS' },
    { key: 'Missouri', text: 'Missouri', value: 'MO' },
    { key: 'Montana', text: 'Montana', value: 'MT' },
    { key: 'Nebraska', text: 'Nebraska', value: 'NE' },
    { key: 'Nevada', text: 'Nevada', value: 'NV' },
    { key: 'NH', text: 'New Hampshire', value: 'NH' },
    { key: 'NJ', text: 'New Jersey', value: 'NJ' },
    { key: 'NM', text: 'Nouveau-Mexique', value: 'NM' },
    { key: 'NY', text: 'New York', value: 'NY' },
    { key: 'NC', text: 'Caroline du Nord', value: 'NC' },
    { key: 'ND', text: 'Dakota du Nord', value: 'ND' },
    { key: 'Ohio', text: 'Ohio', value: 'OH' },
    { key: 'Oklahoma', text: 'Oklahoma', value: 'OK' },
    { key: 'Oregon', text: 'Oregon', value: 'OR' },
    { key: 'Pennsylvania', text: 'Pennsylvanie', value: 'PA' },
    { key: 'RI', text: 'Rhode Island', value: 'RI' },
    { key: 'SC', text: 'Caroline du Sud', value: 'SC' },
    { key: 'SD', text: 'Dakota du Sud', value: 'SD' },
    { key: 'Tennessee', text: 'Tennessee', value: 'TN' },
    { key: 'Texas', text: 'Texas', value: 'TX' },
    { key: 'Utah', text: 'Utah', value: 'UT' },
    { key: 'Vermont', text: 'Vermont', value: 'VT' },
    { key: 'Virginia', text: 'Virginie', value: 'VA' },
    { key: 'Washington', text: 'Washington', value: 'WA' },
    { key: 'WV', text: 'Virginie-Occidentale', value: 'WV' },
    { key: 'Wisconsin', text: 'Wisconsin', value: 'WI' },
    { key: 'Wyoming', text: 'Wyoming', value: 'WY' },
];

const testCardList = [
    { behaviour: 'Approved', number: '4242424242424242', type: 'VISA' },
    { behaviour: 'Approved', number: '4000056655665556', type: 'VISA debi' },
    { behaviour: 'Approved', number: '4000000760000002', type: 'Visa - Brazil' },
    { behaviour: 'Approved', number: '5555555555554444', type: 'Mastercard' },
    { behaviour: 'Approved', number: '5200828282828210', type: 'Mastercard debit' },
    { behaviour: 'Approved', number: '5105105105105100', type: 'Mastercard prepaid' },
    { behaviour: 'Approved', number: '378282246310005', type: 'AMEX' },
    { behaviour: 'Approved', number: '6011111111111117', type: 'Discover' },
    { behaviour: 'Approved', number: '30569309025904', type: 'Diners Club' },
    { behaviour: 'Approved', number: '3530111333300000', type: 'JCB' },
    { behaviour: 'CVV Will Fail', number: '4000000000000101', type: '-' },
    { behaviour: 'Charges Will Fail', number: '4000000000000341', type: '-' },
    { behaviour: 'Card Declined', number: '4000000000000002', type: '-' },
    { behaviour: 'Incorrect CVV', number: '4000000000000127', type: '-' },
    { behaviour: 'Card Declined because fraudlent', number: '4100000000000019', type: '-' },
    { behaviour: 'Card Declined because expired', number: '4000000000000069', type: '-' },
    { behaviour: 'Card Declined because Processing Error', number: '4000000000000119', type: '-' },
    { behaviour: 'Card Declined fails Luhn Check', number: '4242424242424241', type: '-' },
    { behaviour: 'Charge succeed, but risk_level = elevated', number: '4000000000009235', type: '-' },
    { behaviour: '3D secure supported not required', number: '4000000000003055', type: '-' },
    { behaviour: '3D secure supported and required', number: '4000000000003063', type: '-' },
    { behaviour: '3D secure not supported or required', number: '378282246310005', type: '-' },
];

const p2pScheduleOptions = {
    once: 'Once',
    monthly: 'Monthly',
    weekly: 'Weekly',
    yearly: 'Annually',
};

export {
    countryOptions,
    countryOptionsFrench,
    canadaProvinceOptions,
    canadaProvinceOptionsFrench,
    usStateOptions,
    usStateOptionsFrench,
    testCardList,
    p2pScheduleOptions
};
