version: '2.1'

services:
  chimp-web-client-next:
    image: chimp-web-client-next
    build: .
    environment:
      NODE_ENV: dev
      PORT: 6310
    ports:
      - 6310:6310
    ## set your startup file here
    command: node --inspect server.js      